let num1: number = 10;
let num2: number = 5;
let result: number;
result = num1 + num2;
 console.log("Kết quả của phép cộng:", result);
result = num1 - num2;
 console.log("Kết quả của phép trừ:", result);
result = num1 * num2;
 console.log("Kết quả của phép nhân:", result);
result = num1 / num2;
 console.log("Kết quả của phép chia:", result);
result = num1 % num2;
 console.log("Kết quả của phép chia lấy phần dư:", result);
